version: '3.8'

services:
  next-app:
    # 'build' akan menginstruksikan Docker untuk membangun image
    build:
      # 'context' adalah sumber kodenya.
      # Ganti URL ini dengan URL repo GitHub Anda.
      # Anda bisa tentukan branch dengan menambahkan #nama-branch (cth: #main)
      context: https://github.com/yogaprasetia/my-app-next.git#master
      
      # 'dockerfile' adalah nama file instruksi build di dalam repo itu
      dockerfile: Dockerfile
      
    # 'image' adalah nama yang akan diberikan ke image setelah di-build
    image: next-test-app

    # 'ports' memetakan port di server Anda (kiri) ke port di container (kanan)
    # Format: "HOST:CONTAINER"
    ports:
      - "3000:3000"
      
    # 'restart' akan otomatis menyalakan container jika mati (kecuali di-stop manual)
    restart: unless-stopped