version: "3.8"

services:
  nextjs-app:
    image: digipros-prod
    container_name: digipros-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4000:3000"
    volumes:
      - ./public/uploads:/app/public/uploads
    command: "npm run start"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge